" +-------------------------+ "
" |     VIM Config File     |
" +-------------------------+ "


" Menu:
" 1...................Plugins
" 2....................Basics
" 3................Remappings
" 3.......................GUI
" 4.....................Fonts
" 5....................Panels
" 6................MS Windows



" -----[ PLUGINS ]----- "

call plug#begin('~/.vim/plugged')
    Plug 'chriskempson/base16-vim'                          " Best Colors Ever!
    Plug 'tpope/vim-surround'                               " surround keybindings
    Plug 'junegunn/seoul256.vim'                            " seoul colorscheme
    Plug 'HansMartin/vim-plugin-random-colorscheme-picker'  " random  colorschme
    Plug 'ctrlpvim/ctrlp.vim'                               " fuzzy finder for files/buffers ..
    Plug 'ervandew/supertab'                                " tabcompletion
    Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }      " Golang Vim Plugin
call plug#end()



" -----[ BASICS ]----- "

" Color - same color in the beginning
colorscheme seoul256

" Encoding
set encoding=utf-8

" disable any (terminal-)bells
set noeb
set novb
set belloff=all

" Path settings
set backupdir=$HOME/.vim/backups
set noswapfile
set undodir=$HOME/.vim/undo

" Syntax and Lines
syntax enable
set number
set relativenumber
set cursorline

" Tab/Spacing settings
set expandtab           " use spaces instead of tabs
set shiftwidth=4        " number of columns when indenting with > or <
set softtabstop=4       " number of spaces when hitting tab
set autoindent          " set indentation from previous line

" searching...
set ignorecase          " case insensitive
set nohlsearch          " no search highlighting after the search is done
set noshowmatch         " disable that blinking bracket stuff
set wildmenu            " shows menu for tab completion
set incsearch           " search if you type the letters



" -----[ Remappings ]----- "

nnoremap , :            " remap comma to new colon

" When selecting Text, keep the Block selected
vmap < <gv
vmap > >gv

" Remove Trailling Whitespaces
autocmd BufWritePre * :%s/\s\+$//e



" -----[ GUI ]----- "

" This hides the Toolbar, Menubar and left/right scrollbar in gvim
set guioptions -=T
set guioptions -=m
set guioptions -=r
set guioptions -=L



" -----[ Fonts ]----- "
if has("gui_running")
    if has("gui_gtk2")
        set guifont=Hack\ 10
    elseif has("gui_macvim")
        set guifont=Menlo\ Regular:h14
    elseif has("gui_win32")
        set guifont=Consolas:h11:cANSI
    endif
endif



" -----[ Panels ]----- "

" This remaps Ctrl+W +<direction> to Ctr+HJKL for changig the Panel in a
" splitted mode
map <C-h> <C-W>h
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-l> <C-W>l

" This is to get Tabs by using the <leader> Key (Leader Key: '\')
nmap <leader>1 1gt
nmap <leader>2 2gt
nmap <leader>3 3gt
nmap <leader>4 4gt
nmap <leader>5 5gt
nmap <leader>6 6gt



" -----[ MS Windows ]----- "

" Getting the Windows mswin behaviour
if has("win32")
    source $VIMRUNTIME/mswin.vim
    behave mswin
endif
