# some ls aliases
alias ll='ls -al --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ls='ls -CF --color=auto'

# cd stuff
alias ..='cd ..'
alias ...='cd ..'

# grap coloring
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'


# show open ports
alias ports='netstat -tulanp'


alias update='sudo apt-get update'

alias upgrade='sudo apt-get update && sudo apt-get dist-upgrade'


# own tools
alias color='/root/colorize/colorize.py'
alias config='python /root/c0nfigure/c0nfigure.py'

# it sec stuff

# Disassemble using objdump
disas() {
    objdump -M intel -d $@
}
