# some ls aliases
alias ll='ls -al --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ls='ls -CF --color=auto'

# cd stuff
alias ..='cd ..'
alias ...='cd ../..'

# grap coloring
alias grep='grep --color=auto'
alias grep='rg'
alias egrep='egrep --color=auto'


# show open ports
alias ports='netstat -tulanp'


# package manager stuff
alias update='sudo vpm sync'
alias upgrade='sudo vpm update'


# own tools
alias cheat='python /root/tools/cheat/cheat.py'

alias python="python3.6"
alias loadX='xrdb $HOME/.Xresources'

# cat on wings
alias cat='bat'


# brightness settings
alias blow='xbacklight -set 10'
alias bmed='xbacklight -set 45'
alias bhi='xbacklight -set 90'

# it sec stuff

# Disassemble using objdump
disas() {
    objdump -M intel -d $@
}
